In [50]:
import numpy as np 

y_predicted = np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [51]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
     # print(yt,yp)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae
        

In [52]:
mae(y_true,y_predicted)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

In [53]:
# y_predicted-y_true
# np.abs(y_predicted-y_true) #abosulte diff
np.mean(np.abs(y_predicted-y_true)) #mean absolute error


0.5

In [54]:
np.sum(np.abs(y_predicted-y_true)) #total error


2.5

log loss or binary cross entropy

In [55]:
# np.log([0])  #dont define 0 in log only define xlose to zero
np.log([0.0000000000000001])

array([-36.84136149])

In [56]:
epsilon = 1e-15

In [57]:
Y_predicted_new= [max(i,epsilon)for i in y_predicted]
Y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [58]:
Y_predicted_new= [min(i,1-epsilon)for i in Y_predicted_new]
Y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [59]:
Y_predicted_new = np.array(Y_predicted_new)
np.log(Y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [61]:
# np.log(y_predicted)

C:\Users\codea\AppData\Local\Temp\ipykernel_12908\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [62]:
-np.mean(y_true*np.log(Y_predicted_new)+(1-y_true)*np.log(1-Y_predicted_new))

17.2696280766844

In [63]:
def log_loss(y_true,y_prediction):
    epsilon = 1e-15
    Y_predicted_new= [max(i,epsilon)for i in y_predicted]
    Y_predicted_new= [min(i,1-epsilon)for i in Y_predicted_new]
    Y_predicted_new = np.array(Y_predicted_new)
    return -np.mean(y_true*np.log(Y_predicted_new)+(1-y_true)*np.log(1-Y_predicted_new))
    
log_loss(y_true,y_predicted)
    
    

17.2696280766844

Mean Squared Error

In [66]:
def Mse(y_true,y_prediction):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)**2
        
    print("Total error is:",total_error)
    mse = total_error/len(y_predicted)
    print("Mean Squared error is:",mse)
    return mse
        
        
    
Mse(y_true,y_predicted) 

Total error is: 1.83
Mean Squared error is: 0.366


0.366

In [71]:
np.mean(np.square(y_true-y_predicted))

0.366